### ISSUE TITLE
compile into multiple files

### ISSUE THREAD

**Issue by Waog** [Waog/asteroids#21]
... using the AMD compile option and requireJS.

**Comment by mkraenz** [comment]
open todos;
- [x] ~~Create Bugreport~~ Use Package Explorer instead of Navigator...
- [x] figure out what _Exported folders_ are used for (see TypeScript settings under properties)
- [x] reinstall require.js (relates to #19)
- [x] configure TS compiler to use AMD and ES5 and no target file
