### ISSUE TITLE
Establish Github Best Practices

### ISSUE THREAD

**Issue by Waog** [Waog/asteroids#33]
- [x] how to name issues? >> see [wiki](https://github.com/Waog/asteroids/wiki/Github-Best-Practices#issues)
- [x] name bugs differently? >> see [wiki](https://github.com/Waog/asteroids/wiki/Github-Best-Practices#issues)
- [x] how to use labels? >> see [wiki](https://github.com/Waog/asteroids/wiki/Github-Best-Practices#issues)
- [x] how to write commit messages >> see [wiki](https://github.com/Waog/asteroids/wiki/Github-Best-Practices#commit-messages)
- [x] how to use branching? >> see [wiki](https://github.com/Waog/asteroids/wiki/Github-Best-Practices#branching)

**Comment by proSingularity** [comment]
added wiki page https://github.com/Waog/asteroids/wiki/Github-Best-Practices
