### ISSUE TITLE
Error 403 in Travis

### ISSUE THREAD

**Issue by Waog** [Waog/asteroids#41]
When travis is communicating with github, an error 403 (forbidden) occurs occasionally.

See [stackoverflow](http://stackoverflow.com/questions/30447362/travis-ci-throws-status-code-403-when-using-definitelytyped-tsd) for details on possible solutions.

**Comment by mkraenz** [comment]
1. Create Github Access Token.
2. Set it as environment variable TSD_GITHUB_TOKEN in Travis Settings.
